//-----------------------SERVICES------------------------

POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Decoração",
    "description": "Escolha a decoração para sua festa, e nós a montamos.",
    "price": 1400,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
}


###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/67462b7e4d1dafede4a84d16

###
DELETE  http://localhost:3000/api/services/674627e70f4ee60b511b6b7b

###
PUT  http://localhost:3000/api/services/67462b7e4d1dafede4a84d16
Content-Type: application/json

{
    "name": "Teste Atualização",	
    "description": "Test service3",
    "price": 1700,
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&psig=AOvVaw3vbpWEF0EWk7stSBFM7Co5&ust=1732737244243000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLizn7Lj-okDFQAAAAAdAAAAABAE" 
}

//-----------------------PARTY------------------------


###
POST http://localhost:3000/api/party
Content-Type: application/json

{
    "title": "Meu evento 5",
    "author": "Joma 5",
    "description": "Uma festa de aniversário 3",
    "budget": 9000,
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&psig=AOvVaw3vbpWEF0EWk7stSBFM7Co5&ust=1732737244243000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLizn7Lj-okDFQAAAAAdAAAAABAE",
    "services": [
        {
            "name": "test5",
            "description": "Test service3",
            "price": 1600,
            "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&psig=AOvVaw3vbpWEF0EWk7stSBFM7Co5&ust=1732737244243000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLizn7Lj-okDFQAAAAAdAAAAABAE" 
        },
        {
            "name": "test5",
            "description": "Test service 4",
            "price": 1500,
            "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&psig=AOvVaw3vbpWEF0EWk7stSBFM7Co5&ust=1732737244243000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLizn7Lj-okDFQAAAAAdAAAAABAE" 
        }
    ]
}
###
GET http://localhost:3000/api/party

###
GET http://localhost:3000/api/party/674762d6c43bd9d65a364944

###
DELETE  http://localhost:3000/api/party/674762d6c43bd9d65a364944

###
PUT http://localhost:3000/api/party/674762d6c43bd9d65a364945
Content-Type: application/json

{
    "title": "Evento atuallizado teste",
    "author": "Jomas",
    "description": "Uma festa de aniversário atualizada teste",
    "budget": 10000,
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&psig=AOvVaw3vbpWEF0EWk7stSBFM7Co5&ust=1732737244243000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLizn7Lj-okDFQAAAAAdAAAAABAE",
    "services": [
        {
            "name": "test5",
            "description": "Test service3",
            "price": 1600,
            "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&psig=AOvVaw3vbpWEF0EWk7stSBFM7Co5&ust=1732737244243000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLizn7Lj-okDFQAAAAAdAAAAABAE" 
        },
        {
            "name": "test5",
            "description": "Test service 4",
            "price": 1500,
            "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Falphaconvites.com.br%2Ffestas-antes-da-formatura%2F&psig=AOvVaw3vbpWEF0EWk7stSBFM7Co5&ust=1732737244243000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCLizn7Lj-okDFQAAAAAdAAAAABAE" 
        }
    ]
}

//-----------------------USER------------------------

###
POST http://localhost:3000/api/register
Content-Type: application/json
{
    "name": "João Matheus",
    "email": "joao@gmail.com",
    "password": "",
    "confirmpassword": "12345678",
    "image": "sacvsayvcsayvcsayvcsayvcsayvcsay",
    "phone": "85988111723",
    "parties": []
}

###
POST http://localhost:3000/api/login
Content-Type: application/json
{
    "email": "joao@gmail.com",
    "password": "12345678"
}